In [1]:
a=10

In [2]:
b=10

In [3]:
a+b

20

In [4]:
! pip install torch

In [5]:
import torch
t1=torch.tensor([1,2,3])
t1

tensor([1, 2, 3])

In [6]:
t2=torch.tensor([[1,2,3],[4,5,6]])
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
t1=torch.tensor([[1,2],[4,5]])
#t2=torch.tensor([[1,2],[3,4]], device="cuda:0")
t3=torch.tensor([[1,2],[3,4]], dtype=torch.float64)
print(t1)
print(t2)
print(t3)

tensor([[1, 2],
        [4, 5]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [8]:
tf=torch.FloatTensor([[1,2],[3,4]])
tl=torch.LongTensor([[1,2],[3,4]])
tb=torch.ByteTensor([[1,2],[3,4]])

print(tf)
print(tl)
print(tb)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [9]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(type(x))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [10]:
t=torch.from_numpy(x)
print(t)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [11]:
x1=t.numpy()
print(x1)
print(type(x1))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [12]:
print(tf.long())

tensor([[1, 2],
        [3, 4]])


In [13]:
print(tl.float())

tensor([[1., 2.],
        [3., 4.]])


In [14]:
print(tf.byte())

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


텐서 크기 구하기

In [15]:
x=np.arange(1,13).reshape(3,2,2)
x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
tx=torch.from_numpy(x)
tx

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

In [17]:
print('numpy 배열 크기',x.shape)
print('tensor 크기', tx.shape)
print(tx.size())
print(tx.shape[0])
print(tx.size(0))
print(tx.size(1))
print(tx.size(2))
print(tx.size(-1))
print('차원의 수',tx.dim())
print('차원의 수',len(tx.size()))

numpy 배열 크기 (3, 2, 2)
tensor 크기 torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
3
2
2
2
차원의 수 3
차원의 수 3


In [18]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(2,10,2).reshape(2,2)
print(a)
print(b)
ta=torch.from_numpy(a)
tb=torch.from_numpy(b)
print(ta)
print(tb)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 4],
        [6, 8]], dtype=torch.int32)


tensor의 연산

In [19]:
print(ta+tb)
print(ta-tb)
print(ta*tb)
print(ta/tb)
print(ta//tb)
print(ta==tb)
print(ta != tb)
print(ta**tb)

tensor([[ 3,  6],
        [ 9, 12]], dtype=torch.int32)
tensor([[-1, -2],
        [-3, -4]], dtype=torch.int32)
tensor([[ 2,  8],
        [18, 32]], dtype=torch.int32)
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[    1,    16],
        [  729, 65536]], dtype=torch.int32)


In [20]:
ta+tb
ta

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [21]:
print(ta)
print(ta.mul_(tb))   # ta=ta*tb
print(ta)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[ 2,  8],
        [18, 32]], dtype=torch.int32)
tensor([[ 2,  8],
        [18, 32]], dtype=torch.int32)


In [22]:
x=np.arange(1,10).reshape(3,3)
tx=torch.from_numpy(x)
tx

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [23]:
print(tx.sum())
print(x.mean())
print(tx.sum(dim=0))
print(tx.sum(dim=1))
print(tx.sum(dim=-1))

tensor(45)
5.0
tensor([12, 15, 18])
tensor([ 6, 15, 24])
tensor([ 6, 15, 24])


In [24]:
x=np.arange(1,5).reshape(2,2)
t1=torch.from_numpy(x)
y=1
print(t1)
print(t1+y)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 3],
        [4, 5]], dtype=torch.int32)


In [25]:
t2=torch.tensor([1,2])
print(t1)
print(t2)
print(t1+t2)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([1, 2])
tensor([[2, 4],
        [4, 6]])


In [26]:
t3=np.arange(1,7).reshape(2,3)
print(t1)
print(t3)
#print(t1+t3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
[[1 2 3]
 [4 5 6]]


In [27]:
x=np.arange(1,13).reshape(3,2,2)
x=torch.from_numpy(x)
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

In [28]:
print(x.view(3,4))
print(x.view(2,6))
print(x.view(6,2))
print(x.view(3, -1, 2))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=torch.int32)
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)


In [29]:
x1=x.view(3, 1, 4)
print(x1)
x2=x1.squeeze()
print(x2)
x3=x2.unsqueeze(1)
print(x3)

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)


tensor 자르기 & 붙이기

In [30]:
print(x)
print(x.size())

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
torch.Size([3, 2, 2])


In [31]:
print(x[0])
print(x[0,:])
print(x[0,:, :])

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [32]:
print(x[-1])
print(x[-1,:])
print(x[-1, :,:])

tensor([[ 9, 10],
        [11, 12]], dtype=torch.int32)
tensor([[ 9, 10],
        [11, 12]], dtype=torch.int32)
tensor([[ 9, 10],
        [11, 12]], dtype=torch.int32)


In [33]:
print(x[:,0,: ])
print(x[:, :, 1])

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]], dtype=torch.int32)
tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]], dtype=torch.int32)


In [34]:
print(x[1:3,:,:])
print(x[:, 1, :])
print(x[:, :-1, :])

tensor([[[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]], dtype=torch.int32)
tensor([[[ 1,  2]],

        [[ 5,  6]],

        [[ 9, 10]]], dtype=torch.int32)


In [35]:
x=np.arange(1,101).reshape(10,10)
x=torch.from_numpy(x)
print(x)

tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]], dtype=torch.int32)


In [36]:
splits=x.split(4, dim=1)
for s in splits:
    print(s.size())
    print(s)

torch.Size([10, 4])
tensor([[ 1,  2,  3,  4],
        [11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34],
        [41, 42, 43, 44],
        [51, 52, 53, 54],
        [61, 62, 63, 64],
        [71, 72, 73, 74],
        [81, 82, 83, 84],
        [91, 92, 93, 94]], dtype=torch.int32)
torch.Size([10, 4])
tensor([[ 5,  6,  7,  8],
        [15, 16, 17, 18],
        [25, 26, 27, 28],
        [35, 36, 37, 38],
        [45, 46, 47, 48],
        [55, 56, 57, 58],
        [65, 66, 67, 68],
        [75, 76, 77, 78],
        [85, 86, 87, 88],
        [95, 96, 97, 98]], dtype=torch.int32)
torch.Size([10, 2])
tensor([[  9,  10],
        [ 19,  20],
        [ 29,  30],
        [ 39,  40],
        [ 49,  50],
        [ 59,  60],
        [ 69,  70],
        [ 79,  80],
        [ 89,  90],
        [ 99, 100]], dtype=torch.int32)


In [37]:
chunks=x.chunk(5,dim=0)
for c in chunks:
    print(c)
    print(c.size)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=torch.int32)
<built-in method size of Tensor object at 0x00000202A513B3E0>
tensor([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], dtype=torch.int32)
<built-in method size of Tensor object at 0x00000202A515CE60>
tensor([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]], dtype=torch.int32)
<built-in method size of Tensor object at 0x00000202A515CDC0>
tensor([[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=torch.int32)
<built-in method size of Tensor object at 0x00000202A515D590>
tensor([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]], dtype=torch.int32)
<built-in method size of Tensor object at 0x00000202A515D770>


In [38]:
x=np.arange(1,19).reshape(2,3,3)
x=torch.from_numpy(x)
print(x)
indice=torch.LongTensor([2,0])
y=x.index_select(dim=-1, index=indice)
print(y)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=torch.int32)
tensor([[[ 3,  1],
         [ 6,  4],
         [ 9,  7]],

        [[12, 10],
         [15, 13],
         [18, 16]]], dtype=torch.int32)


In [39]:
a=np.arange(1,7).reshape(2,3)
a=torch.from_numpy(a)
print(a)

b=np.arange(7,13).reshape(2,3)
b=torch.from_numpy(b)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [40]:
c=torch.stack([a,b])
print(c)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


In [41]:
d=torch.stack([a,b], dim=-1)
print(d)

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]], dtype=torch.int32)


In [42]:
e=torch.cat([a,b])
print(e)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [43]:
a1=a.view(2,1,3)
print(a1)
a2=a1.expand(2, 3, 3)
print(a2)
print(torch.cat([a1]*3, dim=1))

tensor([[[1, 2, 3]],

        [[4, 5, 6]]], dtype=torch.int32)
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]], dtype=torch.int32)
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]], dtype=torch.int32)


In [44]:


x=torch.randperm(100)
print(x)

tensor([ 2, 50, 48, 98, 56,  1, 85, 58, 11, 33, 29, 87, 93,  8, 61, 45, 26, 66,
        74, 47, 40, 94, 25, 79, 10, 15, 89, 14, 31, 97, 73, 17, 32, 82, 72, 92,
        69, 67, 84, 71, 90, 68, 64, 62, 44, 27, 37, 54,  4,  6, 63, 24, 22, 30,
        86, 39, 96, 57, 99, 83,  3,  9, 46, 13, 38, 53, 65, 59, 75, 91, 19, 16,
        70, 88, 52,  0, 20, 49, 76, 80, 28, 42, 41, 35, 23, 77, 60, 21, 81, 95,
        51, 78, 34, 12,  7, 18,  5, 36, 55, 43])


In [45]:
x=torch.randperm(3**3).reshape(3,3,-1)
print(x)

tensor([[[22, 14, 21],
         [11,  2, 23],
         [ 8,  0, 20]],

        [[ 9,  1, 10],
         [12, 16,  3],
         [18, 15, 19]],

        [[26,  5,  7],
         [25,  6,  4],
         [24, 13, 17]]])


In [46]:
y1=x.argmax(dim=-1)
print(y1)
y2=x.argmax(dim=1)
print(y2)
y3=x.argmax(dim=0)
print(y3)

tensor([[0, 2, 2],
        [2, 1, 2],
        [0, 0, 0]])
tensor([[0, 0, 1],
        [2, 1, 2],
        [0, 2, 2]])
tensor([[2, 0, 0],
        [2, 1, 0],
        [2, 1, 0]])


In [47]:
values, indices=torch.topk(x, k=2, dim=-1)
print(values)
print(indices)
print(values.size())
print(indices.size())

tensor([[[22, 21],
         [23, 11],
         [20,  8]],

        [[10,  9],
         [16, 12],
         [19, 18]],

        [[26,  7],
         [25,  6],
         [24, 17]]])
tensor([[[0, 2],
         [2, 0],
         [2, 0]],

        [[2, 0],
         [1, 0],
         [2, 0]],

        [[0, 2],
         [0, 1],
         [0, 2]]])
torch.Size([3, 3, 2])
torch.Size([3, 3, 2])


In [51]:
x=torch.FloatTensor([i for i in range(9)])

In [52]:
mask=x>4
print(mask)

tensor([False, False, False, False, False,  True,  True,  True,  True])


In [53]:
y=x.masked_fill(mask, value=0)
y

tensor([0., 1., 2., 3., 4., 0., 0., 0., 0.])

In [54]:
a=torch.ones(2,3)
b=torch.zeros(2,3)
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [56]:
y=x.view(3,3)
y

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [58]:
y1=torch.ones_like(y)
y2=torch.zeros_like(y)
print(y1)
print(y2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [48]:
list1=[]
for i in range(9):
    list1.append(i)
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [49]:
list2=[i for i in range(0, 9, 1)]
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8]