In [93]:
import numpy as np  # 벡터 및 행렬의 연산 처리를 위한 라이브러리
import matplotlib.pyplot as plt  # 데이터를 차트나 플롯(plot)으로 그려 주는 라이브러리
import pandas as pd  # 데이터 분석 및 조작을 위한 라이브러리
from sklearn import metrics # 모델 성능 평가

In [94]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'] #데이터 셋의 열이믈
dataset = pd.read_csv('../data/iris.data', names=names) #판다스 데이터프레임으로 데이터 읽어오기
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [95]:
X=dataset.values[:, :-1]
#X=dataset.iloc[:, :-1].values
Y=dataset.values[:, -1]

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, Y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [97]:
X_train[0:10]

array([[5.7, 2.8, 4.1, 1.3],
       [6.3, 2.9, 5.6, 1.8],
       [5.5, 2.5, 4.0, 1.3],
       [6.1, 3.0, 4.9, 1.8],
       [6.3, 3.3, 6.0, 2.5],
       [6.8, 3.2, 5.9, 2.3],
       [6.3, 2.5, 5.0, 1.9],
       [4.8, 3.0, 1.4, 0.3],
       [6.7, 3.1, 5.6, 2.4],
       [5.0, 3.5, 1.3, 0.3]], dtype=object)

In [98]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
X_train=s.fit_transform(X_train)
X_test=s.fit_transform(X_test)
print(X_train[0:5])
print(X_test[0:5])

[[-0.14181318 -0.57617849  0.20630112  0.12750342]
 [ 0.59275871 -0.32746835  1.06390392  0.78136709]
 [-0.38667048 -1.3223089   0.1491276   0.12750342]
 [ 0.34790141 -0.07875821  0.66368928  0.78136709]
 [ 0.59275871  0.6673722   1.292598    1.69677623]]
[[ 0.87884369 -0.08231641  0.4812921   0.42568381]
 [-1.35749963  0.48756643 -1.07965525 -1.32186025]
 [ 0.64343913  0.10764454  0.70428458  1.09781614]
 [ 0.87884369  0.29760548  1.0387733   1.76994847]
 [ 0.52573685 -0.08231641  0.92727706  0.82896321]]


In [99]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=50)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [100]:
from sklearn.metrics import accuracy_score
y_pred=knn.predict(X_test)
print('정확도:{}'.format(accuracy_score(y_test, y_pred)))

정확도:0.9333333333333333


In [101]:
print(y_pred[0:10])
print(y_test[0:10])

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor']
['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor']


In [102]:
k=50

acc_array=np.zeros(k)
for i in np.arange(2, k+1,1):
    classifier=KNeighborsClassifier(n_neighbors=i).fit(X_train, y_train)
    y_pred=classifier.predict(X_test)
    acc=metrics.accuracy_score(y_test, y_pred)
    acc_array[i-1]=acc

max_acc=np.amax(acc_array)
acc_list=list(acc_array)
k=acc_list.index(max_acc)
print(acc_list)
print('정확도 {}으로 최적의 K는 {}입니다'.format(max_acc, k+2))

[0.0, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9666666666666667, 1.0, 0.9666666666666667, 1.0, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333, 0.9333333333333333]
정확도 1.0으로 최적의 K는 8입니다


SVM

In [103]:
#! pip install  tensorflow

In [104]:
from sklearn import svm
from sklearn import metrics
from sklearn import datasets
from sklearn import model_selection

import tensorflow as tf

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'

# ① TF_CPP_MIN_LOG_LEVEL이라는 환경 변수를 사용하여 
# 로깅을 제어(기본값은 0으로 모든 로그가 표시되며, 
# INFO 로그를 필터링하려면 1, 
# WARNING 로그를 필터링하려면 2, 
# ERROR 로그를 추가로 필터링하려면 3으로 설정) 
# 환경 변수 값을 바꾸어 가면서 실행해 보는 것도 학습에 좋은 방법

In [105]:
iris=datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [106]:
x_train, x_test, y_train, y_test=model_selection.train_test_split(iris.data,
                                                                  iris.target,
                                                                  test_size=0.4,
                                                                  random_state=42)

In [107]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(90, 4) (90,) (60, 4) (60,)


In [108]:
svm=svm.SVC(kernel='linear', C=1.0, gamma=0.5)
svm.fit(x_train, y_train)
prediction=svm.predict(x_test)
score=metrics.accuracy_score(y_test, prediction)
print('정확도:{0:f}'.format(score))

정확도:1.000000


결정트리

In [111]:
import pandas as pd
df=pd.read_csv('../data/titainic_train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [118]:
df1=df[['Pclass','Sex','Age','SibSp','Parch','Fare','Survived']]
df1['Sex']=df['Sex'].map({'male':0, 'female':1})
df1

C:\Users\it\AppData\Local\Temp\ipykernel_15484\2487270573.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Sex']=df['Sex'].map({'male':0, 'female':1})


Pclass  Sex   Age  SibSp  Parch     Fare  Survived
0         3    0  22.0      1      0   7.2500         0
1         1    1  38.0      1      0  71.2833         1
2         3    1  26.0      0      0   7.9250         1
3         1    1  35.0      1      0  53.1000         1
4         3    0  35.0      0      0   8.0500         0
..      ...  ...   ...    ...    ...      ...       ...
886       2    0  27.0      0      0  13.0000         0
887       1    1  19.0      0      0  30.0000         1
888       3    1   NaN      1      2  23.4500         0
889       1    0  26.0      0      0  30.0000         1
890       3    0  32.0      0      0   7.7500         0

[891 rows x 7 columns]

In [119]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    int64  
 2   Age       714 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Survived  891 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 48.9 KB


In [120]:
df1.dropna()
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    int64  
 2   Age       714 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Survived  891 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 48.9 KB


In [122]:
X=df1.drop('Survived', axis=1)
y=df1['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=1)

In [124]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(668, 6) (668,) (223, 6) (223,)


In [130]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [131]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [133]:
y_predict=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

0.7757847533632287