In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

'apple!' : input_data => apple, output_data=pple!

In [4]:
input_str='apple'
label_str='pple!'
char_set=sorted(list(set(input_str+label_str)))
print(char_set)
char_set_size=len(char_set)
print(char_set_size)

['!', 'a', 'e', 'l', 'p']
5


In [5]:
input_size=5
hidden_size=5
output_size=5
learning_rate=0.1

In [6]:
char_to_index=dict((c, i) for i, c in enumerate(char_set))
print(char_to_index)
# char_list=[c for c in char_set]

# char_list=[]
# for c in char_set:
#     char_set.append(c)


{'!': 0, 'a': 1, 'e': 2, 'l': 3, 'p': 4}


In [10]:
char_to_index.items()
# char_to_index.values()
# char_to_index.keys()

dict_items([('!', 0), ('a', 1), ('e', 2), ('l', 3), ('p', 4)])

In [11]:
index_to_char={}
for key, value in char_to_index.items():
    index_to_char[value]=key

print(index_to_char)


{0: '!', 1: 'a', 2: 'e', 3: 'l', 4: 'p'}


In [12]:
x_data=[char_to_index[c] for c in input_str] #apple
y_data=[char_to_index[c] for c in label_str] #pple!

print(x_data)
print(y_data)

[1, 4, 4, 3, 2]
[4, 4, 3, 2, 0]


In [14]:
x_one_hot=[np.eye(char_set_size)[x] for x in x_data]
print(x_one_hot)


[array([0., 1., 0., 0., 0.]), array([0., 0., 0., 0., 1.]), array([0., 0., 0., 0., 1.]), array([0., 0., 0., 1., 0.]), array([0., 0., 1., 0., 0.])]


In [15]:
X=torch.FloatTensor(x_one_hot)
Y=torch.LongTensor(y_data)
print(X)
print(Y)

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])
tensor([4, 4, 3, 2, 0])


C:\Users\it\AppData\Local\Temp\ipykernel_16216\3424434832.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:281.)
  X=torch.FloatTensor(x_one_hot)


In [17]:
#nn.RNN(input_size, hidden_size, output_size)
class Net(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Net, self).__init__()
        self.rnn=nn.RNN(input_size, hidden_size, batch_first=True)
        # batch_first : 입력데이터의 배치의 차원의 위치를 설정
        # (배치크기, 시퀀스 길이, 특징 수)
        #  입력의 형태가 (32, 10, 50) :  배치의 크기 32, 시퀀스 길이 : 10, 특징의 수 50
        self.fc=nn.Linear(hidden_size,output_size, bias=True)

    def forward(self, x):
        x, _status=self.rnn(x)
        x=self.fc(x)
        return x

In [18]:
model=Net(input_size, hidden_size, output_size)
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(), lr=learning_rate)

In [19]:
output=model(X)
print(output)
print(output.size())

tensor([[ 0.1431,  0.4232,  0.3147, -0.1068,  0.6875],
        [ 0.2820,  0.3162,  0.0334, -0.1131,  0.4782],
        [ 0.1774,  0.1665,  0.0727, -0.1738,  0.3338],
        [-0.0381,  0.2873,  0.0340, -0.2354,  0.3562],
        [ 0.1502,  0.4041,  0.3510, -0.3653,  0.4371]],
       grad_fn=<AddmmBackward0>)
torch.Size([5, 5])
