In [1]:
import torch
import torch.nn.functional as F

In [3]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [7]:
z=torch.rand(3, 5, requires_grad=True)
print(z)
y_hat=F.softmax(z, dim=1)
print(y_hat)
print(y_hat.sum(dim=1))

tensor([[0.3395, 0.0990, 0.7017, 0.6098, 0.9200],
        [0.4735, 0.3662, 0.4852, 0.6101, 0.7263],
        [0.5908, 0.8600, 0.6470, 0.4912, 0.0135]], requires_grad=True)
tensor([[0.1582, 0.1244, 0.2273, 0.2073, 0.2827],
        [0.1871, 0.1681, 0.1893, 0.2145, 0.2410],
        [0.2069, 0.2708, 0.2189, 0.1873, 0.1162]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [26]:
y=torch.randint(5,(3,)).long()
print(y)
print(y_hat)
y_one_hot=torch.zeros_like(y_hat)
print(y_one_hot)
print(y.unsqueeze(1))
y_one_hot.scatter_(1,y.unsqueeze(1),1)
print(y_one_hot)

tensor([0, 1, 4])
tensor([[0.1582, 0.1244, 0.2273, 0.2073, 0.2827],
        [0.1871, 0.1681, 0.1893, 0.2145, 0.2410],
        [0.2069, 0.2708, 0.2189, 0.1873, 0.1162]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0],
        [1],
        [4]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]])


import torch.nn as nn
import torch.optim as optim

In [27]:
import torch.nn as nn
import torch.optim as optim

In [28]:
torch.manual_seed(1)
x_data=[[1,2,1,1],
        [2,1,3,2],
        [3,1,3,4],
        [4,1,5,5],
        [1,7,5,5],
        [1,2,5,6],
        [1,6,6,6],
        [1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]

In [30]:
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8])


In [32]:
y_one_hot=torch.zeros(8,3)
print(y_one_hot)
y_one_hot.scatter_(1, y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [33]:
w=torch.zeros((4,3), requires_grad=True)
b=torch.zeros((1,3), requires_grad=True)
print(w)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [34]:
optimizer=optim.SGD([w,b], lr=0.1)
epochs=10001

In [35]:
for epoch in range(epochs):
    y_hat=F.softmax(x_train.matmul(w)+b, dim=1)
    cost=(y_one_hot* -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(epoch, cost.item())

0 1.0986123085021973
100 0.7041995525360107
200 0.6229996085166931
300 0.5657169222831726
400 0.5152913331985474
500 0.46766167879104614
600 0.4212779700756073
700 0.3754016160964966
800 0.3297654986381531
900 0.2850721478462219
1000 0.2481546849012375
1100 0.23267611861228943
1200 0.22139869630336761
1300 0.21112915873527527
1400 0.20173649489879608
1500 0.1931133270263672
1600 0.18516966700553894
1700 0.1778293251991272
1800 0.17102724313735962
1900 0.16470739245414734
2000 0.15882128477096558
2100 0.15332657098770142
2200 0.14818626642227173
2300 0.14336799085140228
2400 0.1388428956270218
2500 0.13458555936813354
2600 0.13057351112365723
2700 0.12678645551204681
2800 0.12320639193058014
2900 0.1198171004652977
3000 0.11660401523113251
3100 0.11355391144752502
3200 0.11065512150526047
3300 0.10789669305086136
3400 0.10526886582374573
3500 0.10276280343532562
3600 0.10037018358707428
3700 0.09808389842510223
3800 0.09589694440364838
3900 0.0938030406832695
4000 0.09179650247097015
41

In [37]:
y_hat=F.softmax(x_train.matmul(w)+b, dim=1)
print(y_hat)
print(y_one_hot)

tensor([[7.9508e-11, 6.5690e-06, 9.9999e-01],
        [1.7811e-04, 1.9474e-02, 9.8035e-01],
        [1.1670e-13, 4.1809e-02, 9.5819e-01],
        [6.1379e-10, 9.6248e-01, 3.7520e-02],
        [7.2622e-02, 9.2453e-01, 2.8516e-03],
        [3.8537e-02, 9.6146e-01, 7.0804e-08],
        [9.1230e-01, 8.7705e-02, 8.1008e-08],
        [9.9212e-01, 7.8797e-03, 5.7659e-11]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [38]:
for y in y_hat:
    print(y.argmax().item())

2
2
2
1
1
1
0
0


In [41]:
import sklearn.datasets as datasets
iris=datasets.load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [42]:
x_train=torch.FloatTensor(iris.data)
y_train=torch.LongTensor(iris.target)
print(x_train.size())
print(y_train.size())

torch.Size([150, 4])
torch.Size([150])


In [44]:
model=nn.Linear(4,3)
optimizer=optim.SGD(model.parameters(), lr=0.1)
epochs=10001

In [45]:
for epoch in range(epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print('Epoch:', epoch,'Cost:', cost.item())

Epoch: 0 Cost: 1.7532501220703125
Epoch: 100 Cost: 0.4651300609111786
Epoch: 200 Cost: 0.2666434347629547
Epoch: 300 Cost: 0.22042623162269592
Epoch: 400 Cost: 0.19214804470539093
Epoch: 500 Cost: 0.1727110594511032
Epoch: 600 Cost: 0.15846771001815796
Epoch: 700 Cost: 0.1475398689508438
Epoch: 800 Cost: 0.1388620287179947
Epoch: 900 Cost: 0.13178418576717377
Epoch: 1000 Cost: 0.12588708102703094
Epoch: 1100 Cost: 0.12088768184185028
Epoch: 1200 Cost: 0.11658785492181778
Epoch: 1300 Cost: 0.1128445565700531
Epoch: 1400 Cost: 0.1095518246293068
Epoch: 1500 Cost: 0.10662936419248581
Epoch: 1600 Cost: 0.10401521623134613
Epoch: 1700 Cost: 0.10166074335575104
Epoch: 1800 Cost: 0.09952720999717712
Epoch: 1900 Cost: 0.0975833311676979
Epoch: 2000 Cost: 0.0958036258816719
Epoch: 2100 Cost: 0.09416702389717102
Epoch: 2200 Cost: 0.09265591949224472
Epoch: 2300 Cost: 0.09125566482543945
Epoch: 2400 Cost: 0.08995378017425537
Epoch: 2500 Cost: 0.08873960375785828
Epoch: 2600 Cost: 0.08760404586791

In [48]:
predict=model(x_train)
#print(predict)

accuracys=[]

for i in range(len(predict)):
    accuracys.append(y_train[i]==predict[i].argmax())

print(len(accuracys), torch.FloatTensor(accuracys).sum())
print(torch.FloatTensor(accuracys).sum()/len(accuracys))

150 tensor(147.)
tensor(0.9800)
