In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [8]:
model=LinearRegressionModel()
print(model)
optimizer=optim.SGD(model.parameters(), lr=0.01)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [10]:
epochs=2001

for epoch in range(epochs):
    y=model(x_data)
    cost=F.mse_loss(y, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(epoch, cost.item(), list(model.parameters()))

0 3.5098217665563425e-08 [Parameter containing:
tensor([[1.9999]], requires_grad=True), Parameter containing:
tensor([1.0004], requires_grad=True)]
100 1.7964021381544626e-08 [Parameter containing:
tensor([[1.9999]], requires_grad=True), Parameter containing:
tensor([1.0003], requires_grad=True)]
200 9.116865484770642e-09 [Parameter containing:
tensor([[1.9999]], requires_grad=True), Parameter containing:
tensor([1.0002], requires_grad=True)]
300 4.614093995769508e-09 [Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0002], requires_grad=True)]
400 2.3940629478858e-09 [Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0001], requires_grad=True)]
500 1.2107648217352107e-09 [Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0001], requires_grad=True)]
600 6.080881354009193e-10 [Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containi

In [15]:
predict=model(torch.FloatTensor([[7],[8]]))
print(predict)

tensor([[15.0000],
        [17.0000]], grad_fn=<AddmmBackward0>)


In [32]:
import pandas as pd
df=pd.read_csv('../data/data-01-test-score.csv', header=None)
x_data=df.values[:,:-1]
t_data=df.values[:,-1]
print(x_data.shape, t_data.shape)
t_data=t_data.reshape(-1, 1)
print(x_data.shape, t_data.shape)
print(type(x_data), type(t_data))

x_data1=torch.from_numpy(x_data).float()
t_data1=torch.from_numpy(t_data).float()

print(type(x_data1), type(t_data1))

indim=x_data1.size(1)
print(indim)

(25, 3) (25,)
(25, 3) (25, 1)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'torch.Tensor'> <class 'torch.Tensor'>
3


In [29]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(indim,1)

    def forward(self, x):
        return self.linear(x)

In [30]:
model=MultiLinearRegressionModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [37]:
epochs=200001
for epoch in range(epochs):
    y=model(x_data1)
    cost=F.mse_loss(y, t_data1)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100==0:
        print(epoch, cost.item(), list(model.parameters()))

0 6.09653377532959 [Parameter containing:
tensor([[0.3682, 0.5357, 1.1109]], requires_grad=True), Parameter containing:
tensor([-0.0736], requires_grad=True)]
100 6.096465587615967 [Parameter containing:
tensor([[0.3681, 0.5357, 1.1109]], requires_grad=True), Parameter containing:
tensor([-0.0736], requires_grad=True)]
200 6.096392631530762 [Parameter containing:
tensor([[0.3681, 0.5357, 1.1110]], requires_grad=True), Parameter containing:
tensor([-0.0736], requires_grad=True)]
300 6.096324920654297 [Parameter containing:
tensor([[0.3681, 0.5356, 1.1110]], requires_grad=True), Parameter containing:
tensor([-0.0736], requires_grad=True)]
400 6.096269607543945 [Parameter containing:
tensor([[0.3680, 0.5356, 1.1111]], requires_grad=True), Parameter containing:
tensor([-0.0736], requires_grad=True)]
500 6.096203804016113 [Parameter containing:
tensor([[0.3680, 0.5356, 1.1112]], requires_grad=True), Parameter containing:
tensor([-0.0737], requires_grad=True)]
600 6.096146106719971 [Paramete

In [38]:
x=torch.FloatTensor([[75,85,90],[90,85,75]])
model(x)

tensor([[173.2063],
        [161.6626]], grad_fn=<AddmmBackward0>)